site_name: DeepTechRadar2026
site_url: https://christianchabrerie.github.io/DeepTechRadar2026/

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: markmap
          class: markmap
          format: !!python/name:pymdownx.superfences.fence_div_format

# Load the visualization engine from the web
extra_javascript:
  - https://cdn.jsdelivr.net/npm/markmap-autoloader@0.17.0/dist/index.js

extra_css:
  - https://cdn.jsdelivr.net/npm/markmap-toolbar@0.17.0/dist/style.css
  - stylesheets/extra.css


